package iotc.db;
// Generated 2012/12/11 18:19:43 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Command generated by hbm2java
 */
@Entity
@EntityListeners(iotc.event.HibernateEventListener.class)
@Table(name="command"
    ,catalog="iotc"
)
public class Command  implements java.io.Serializable {


     private Integer id;
     private Device device;
     private String name;
     private int type;
     private int power;
     private String command;
     private String aliasName;
     private Set tasks = new HashSet(0);
     private Set logs = new HashSet(0);

    public Command() {
    }


    public Command(Device device, String name, int type, int power, String command) {
        this.device = device;
        this.name = name;
        this.type = type;
        this.power = power;
        this.command = command;
    }
    public Command(Device device, String name, int type, int power, String command, String aliasName, Set tasks, Set logs) {
       this.device = device;
       this.name = name;
       this.type = type;
       this.power = power;
       this.command = command;
       this.aliasName = aliasName;
       this.tasks = tasks;
       this.logs = logs;
    }

     @Id @GeneratedValue(strategy=IDENTITY)

    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="device_id", nullable=false)
    public Device getDevice() {
        return this.device;
    }

    public void setDevice(Device device) {
        this.device = device;
    }

    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name="type", nullable=false)
    public int getType() {
        return this.type;
    }

    public void setType(int type) {
        this.type = type;
    }

    @Column(name="power", nullable=false)
    public int getPower() {
        return this.power;
    }

    public void setPower(int power) {
        this.power = power;
    }

    @Column(name="command", nullable=false, length=65535)
    public String getCommand() {
        return this.command;
    }

    public void setCommand(String command) {
        this.command = command;
    }

    @Column(name="alias_name")
    public String getAliasName() {
        return this.aliasName;
    }

    public void setAliasName(String aliasName) {
        this.aliasName = aliasName;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="ref_task_command", catalog="iotc", joinColumns = {
        @JoinColumn(name="command", nullable=false, updatable=false) }, inverseJoinColumns = {
        @JoinColumn(name="task", nullable=false, updatable=false) })
    public Set getTasks() {
        return this.tasks;
    }

    public void setTasks(Set tasks) {
        this.tasks = tasks;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="command")
    public Set getLogs() {
        return this.logs;
    }

    public void setLogs(Set logs) {
        this.logs = logs;
    }




}


