package iotc.db;
// Generated 2012/12/11 18:19:43 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SensorType generated by hbm2java
 */
@Entity
@EntityListeners(iotc.event.JpaEventListener.class)
@Table(name="sensor_type"
    ,catalog="iotc"
)
public class SensorType  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String unit;
     private Set sensors = new HashSet(0);

    public SensorType() {
    }


    public SensorType(String name, String unit) {
        this.name = name;
        this.unit = unit;
    }
    public SensorType(String name, String unit, Set sensors) {
       this.name = name;
       this.unit = unit;
       this.sensors = sensors;
    }

     @Id @GeneratedValue(strategy=IDENTITY)

    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name="unit", nullable=false, length=32)
    public String getUnit() {
        return this.unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="sensorType")
    public Set getSensors() {
        return this.sensors;
    }

    public void setSensors(Set sensors) {
        this.sensors = sensors;
    }

    @Override
    public String toString() {
        return this.name;
    }
}


