package iotc.db;
// Generated 2012/12/11 18:19:43 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * StatisticValue generated by hbm2java
 */
@Entity
@EntityListeners(iotc.event.JpaEventListener.class)
@Table(name="statistic_value"
    ,catalog="iotc"
)
public class StatisticValue  implements java.io.Serializable {


     private Integer id;
     private Date timestamp;
     private StatisticalMethod statisticalMethod;
     private double value;

    public StatisticValue() {
    }

    public StatisticValue(StatisticalMethod statisticalMethod, double value) {
       this.statisticalMethod = statisticalMethod;
       this.value = value;
    }

     @Id @GeneratedValue(strategy=IDENTITY)

    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }
    @Version@Temporal(TemporalType.TIMESTAMP)
    @Column(name="timestamp", nullable=false, length=19)
    public Date getTimestamp() {
        return this.timestamp;
    }

    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="method", nullable=false)
    public StatisticalMethod getStatisticalMethod() {
        return this.statisticalMethod;
    }

    public void setStatisticalMethod(StatisticalMethod statisticalMethod) {
        this.statisticalMethod = statisticalMethod;
    }

    @Column(name="value", nullable=false, precision=22, scale=0)
    public double getValue() {
        return this.value;
    }

    public void setValue(double value) {
        this.value = value;
    }




}


