package iotc.db;
// Generated 2012/12/11 18:19:43 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StatisticalMethod generated by hbm2java
 */
@Entity
@EntityListeners(iotc.event.HibernateEventListener.class)
@Table(name="statistical_method"
    ,catalog="iotc"
)
public class StatisticalMethod  implements java.io.Serializable {


     private Integer id;
     private String method;
     private int timespan;
     private Set sensors = new HashSet(0);
     private Set statisticValues = new HashSet(0);
     private Set terms = new HashSet(0);

    public StatisticalMethod() {
    }


    public StatisticalMethod(String method, int timespan) {
        this.method = method;
        this.timespan = timespan;
    }
    public StatisticalMethod(String method, int timespan, Set sensors, Set statisticValues, Set terms) {
       this.method = method;
       this.timespan = timespan;
       this.sensors = sensors;
       this.statisticValues = statisticValues;
       this.terms = terms;
    }

     @Id @GeneratedValue(strategy=IDENTITY)

    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name="method", nullable=false, length=65535)
    public String getMethod() {
        return this.method;
    }

    public void setMethod(String method) {
        this.method = method;
    }

    @Column(name="timespan", nullable=false)
    public int getTimespan() {
        return this.timespan;
    }

    public void setTimespan(int timespan) {
        this.timespan = timespan;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="ref_method_sensor", catalog="iotc", joinColumns = {
        @JoinColumn(name="method", nullable=false, updatable=false) }, inverseJoinColumns = {
        @JoinColumn(name="sensor", nullable=false, updatable=false) })
    public Set getSensors() {
        return this.sensors;
    }

    public void setSensors(Set sensors) {
        this.sensors = sensors;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="statisticalMethod")
    public Set getStatisticValues() {
        return this.statisticValues;
    }

    public void setStatisticValues(Set statisticValues) {
        this.statisticValues = statisticValues;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="ref_term_method", catalog="iotc", joinColumns = {
        @JoinColumn(name="method", nullable=false, updatable=false) }, inverseJoinColumns = {
        @JoinColumn(name="term", nullable=false, updatable=false) })
    public Set getTerms() {
        return this.terms;
    }

    public void setTerms(Set terms) {
        this.terms = terms;
    }




}


